config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'

  namespace :authors do
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end


  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about
    get 'contact' => 'pages#contact', as: :contact
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'post#show', as: :post

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable  and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  body         :text(65535)
#  description  :text(65535)
#  slug         :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  author_id    :integer
#  published    :boolean          default(FALSE)
#  published_at :datetime
#

class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author

  scope :most_recent, -> { order(id: :desc) }
  scope :published, -> { where(published: true) }

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'author'
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/posts_controller.rb
module Authors

  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      # @posts = Post.all
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    def publish
      @post.update(published: true, published_at: Time.now)
      redirect_to authors_posts_url
    end

    def unpublish
      @post.update(published: false, published_at: nil)
      redirect_to authors_posts_url
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :description)
    end
  end

end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < BlogController
    def about
    end

    def contact
    end
  end
end

app/controllers/blog/posts_controller.rb
module Blog

  class PostsController < BlogController

    # GET /posts
    # GET /posts.json
    def index
      # @posts = Post.all
      # @posts = Post.paginate(:page => params[:page])
    @posts = Post.most_recent.published.paginate(:page => params[:page], per_page: 2 )
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = Post.friendly.find(params[:id])
    end

  end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.erb
<%= form_with(model: post, local: true, url: url) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
  <td>
    <%= link_to post.title, authors_post_path(post) %>
  </td>
  <td>
    <%= link_to 'Delete', authors_post_path(post), class: 'btn btn-danger pull-right action-button', method: 'delete',
                data: {
                    confirm: 'Are you sure?'
                }%>
    <%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-success pull-right action-button' %>
    <% if post.published? %>
        <%= link_to 'Unpublish', unpublish_authors_post_path(post), class: 'btn btn-warning pull-right action-button', method: 'put'  %>
    <% else %>
        <%= link_to 'Publish', publish_authors_post_path(post), class: 'btn btn-primary pull-right action-button', method: 'put' %>
    <% end %>

  </td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide('page_title', "Edit #{@post.title}") %>
<% provide(:authors, 'active') %>

<h1>Editing @post.title</h1>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

<%= link_to 'Show', authors_post_path(@post) %> |
<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:authors, 'active') %>

<p id="notice"><%= notice %></p>

<div class="row">
    <h1>Posts</h1>
</div>

<div class="container">
  <table class="table table-striped">
    <tr>
      <th colspan="3">
        Title
        <%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary pull-right' %>
      </th>

    </tr>
    <%= render @posts %>
  </table>

</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'New Post') %>
<% provide(:authors, 'active') %>

<h1>New Post</h1>

<%= render 'form', post: @post, url: authors_posts_url %>

<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:authors, 'active') %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<%= link_to 'Edit', edit_authors_post_path(@post) %> |
<%= link_to 'Back', authors_posts_path %>

app/views/blog/pages/about.html.erb
<% provide(:page_title, 'About') %>
<% provide(:about_active, 'active') %>

<h1>About Page</h1>

app/views/blog/pages/contact.html.erb
<% provide(:page_title, 'Contact') %>
<% provide(:contact_active, 'active') %>

<h1>Contact Page</h1>

app/views/blog/posts/_post.html.erb
<div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"> <%= link_to post.title, post %> </h3>
    </div>
    <div class="panel-body">
      <p>
        <%= post.description %>
      </p>
    </div>
  </div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'All Posts') %>
<% provide(:blog_active, 'active') %>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <h1>Posts</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <%= render @posts %>
  </div>
  <%= will_paginate @posts %>
</div>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:blog_active, 'active') %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class='<%= "#{yield(:blog_active)}" %>'>
        <%= link_to 'Blog',  root_path, class: 'nav-link' %>
      </li>
      <li class="<%= "#{yield(:about_active)}" %>">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>
      <li class='<%= "#{yield(:contact_active)}" %>'>
        <%= link_to 'Contact', contact_path, class: 'nav-link' %>
      </li>
      <% if author_signed_in? %>
          <li class="<%= "#{yield(:authors)}" %>">
            <%= link_to 'My Posts', authors_posts_path, class: 'nav-link' %>
          </li>
          <li class="text-danger">
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: 'nav-link ' %>
          </li>
      <% end %>
      <% if !author_signed_in? %>
          <li class="<%= "#{yield(:authors)}" %>">
            <%= link_to 'Sign in', new_author_session_path, class: 'nav-link' %>
          </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | RubyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track':  'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | RubyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track':  'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>

  </body>
</html>